# Generated by Django 4.1 on 2022-09-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('nit', models.IntegerField()),
                ('cuidad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=40)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=20)),
                ('roles', models.CharField(max_length=30)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apptransacciones.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=40)),
                ('monto', models.IntegerField()),
                ('tipo', models.CharField(max_length=40)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apptransacciones.empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apptransacciones.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apptransacciones.empresas'),
        ),
    ]
