# Generated by Django 4.1 on 2022-09-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransacciones', '0002_remove_usuarios_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cuidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='sector',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='roles',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
