# Generated by Django 4.1 on 2022-09-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptransacciones', '0003_alter_empleados_id_alter_empresas_cuidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
